(eval-when-compile    (require 'color-theme))
(defun my-deep-blue ()
  "Color theme by upi=PA0024320, created 2011-03-31."
  (interactive)
  (color-theme-install
   '(my-deep-blue
     ;;((background-color . "#102e4e")
     ;;((background-color . "#1C1C1C")
     ((background-color . "black")
     ;;((background-color . "#F0F0F0")
      ;;((background-color . "#07233F")
      ;;((background-color . "#191919")
;;      (background-mode . dark)
      ;;(background-toolbar-color . "#e79ddf7ddf7d")
      (border-color . "black")
      ;;(bottom-toolbar-shadow-color . "#8e3886178617")
      (cursor-color . "green")
      (foreground-color . "#d3d7cf")
      (mouse-color . "white")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#ffffffffffff")
      (vc-annotate-very-old-color . "#0046FF")
    (viper-saved-cursor-color-in-replace-mode . "Red3"))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Gray30"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Gray30"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Gray30"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Gray30"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eshell-ls-archive-face ((t (:bold t :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "gray85"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "gray85" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "Cyan" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "gray85"))))
     (eshell-ls-product-face ((t (:foreground "gray85"))))
     (eshell-ls-readonly-face ((t (:foreground "gray70"))))
     (eshell-ls-special-face ((t (:bold t :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :weight bold))))
     (eshell-ls-text-face ((t (:foreground "gray85"))))
     (eshell-ls-todo-face ((t (:bold t :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "gray85"))))
     (eshell-prompt-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :weight bold))))
     (eshell-test-ok-face ((t (:bold t :weight bold))))
     

     (font-lock-builtin-face ((t (:foreground "yellow"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#827D68"))))
     (font-lock-comment-face ((t (:foreground "#827D68"))))
     (font-lock-constant-face ((t (:foreground "red"))))
     (font-lock-doc-string-face ((t (:foreground "#A92323"))))
     (font-lock-function-name-face ((t (:foreground "#AADFFF"))))
     (font-lock-keyword-face ((t (:foreground "#AADFFF"))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "yellow" :weight bold))))
     (font-lock-other-type-face ((t (:bold t :foreground "yellow" :weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "#ad7fa8"))))
     (font-lock-string-face ((t (:foreground "#d78787"))))
     (font-lock-type-face ((t (:foreground "yellow"))))
     (font-lock-variable-name-face ((t (:foreground "#d3d7cf"))))
     ;;(fringe ((t (:background "#333"))))

     ;; some python specific font lock themes
     (py-class-name-face ((t (:foreground "#A6E22E"))))
     (py-pseudo-keyword-face ((t (:foreground "#FD9720"))))
     (py-decorators-face ((t (:foreground "#AADFFF"))))
     (py-builtins-face ((t (:foreground "#AADFFF"))))
     ;;(py-XXX-tag-face ((t (:foreground "#7C7C7C"))))

     
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#ffffff" :foreground "#000000"))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue" :weight bold))))
     (hi-green ((t (:background "green"))))
     (hi-green-b ((t (:bold t :foreground "green" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red" :weight bold))))
     (hi-yellow ((t (:background "yellow"))))
     (highlight ((t (:background "darkgreen"))))
     (highlight-changes-delete-face ((t (:foreground "gray85" :underline t))))
     (highlight-changes-face ((t (:foreground "gray85"))))
     (highlight-symbol-face ((t (:background "gray30"))))
     (highline-face ((t (:background "#3c5473"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (holiday-face ((t (:background "pink" :foreground "green"))))
     (html-helper-bold-face ((t (:bold t :weight bold))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "gray85" :underline t))))
     (html-helper-italic-face ((t (:bold t :foreground "yellow" :weight bold))))
     (html-helper-underline-face ((t (:underline t))))
     (html-tag-face ((t (:bold t :foreground "#f0e68c" :weight bold))))
     (hyper-apropos-documentation ((t (:foreground "white"))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "gray85" :weight bold))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "gray85"))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "yellow"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-subdir-face ((t (:foreground "red"))))
     (info-header-node ((t (:italic t :bold t :foreground "DeepSkyBlue1" :slant italic :weight bold))))
     (info-header-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-menu-star ((t (:foreground "wheat" :underline t))))
     (info-node ((t (:italic t :bold t :foreground "DeepSkyBlue1" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (info-title-2 ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (info-title-3 ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (info-title-4 ((t (:bold t :weight bold :family "helv"))))
     (info-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t (:bold t :foreground "yellow" :weight bold))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (linum ((t (:foreground "grey70"))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (log-view-file-face ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message-face ((t (:background "grey85"))))
     (magenta ((t (:foreground "gray85"))))
     (makefile-space-face ((t (:background "hotpink" :foreground "white"))))
     ;;(minibuffer-prompt ((t (:foreground "cyan"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     ;;(mode-line ((t (:background "RoyalBlue4" :foreground "mistyRose" :box (:line-width 1 :style released-button)))))
     ;;(mode-line ((t (:background "RoyalBlue4" :foreground "Gold" :box (:line-width 1 :style released-button)))))
     ;;(mode-line ((t (:background "#8B0000" :foreground "Gold" :box (:line-width 1 :style released-button)))))
     (mode-line ((t (:background "RoyalBlue4" :foreground "Gold" :box (:line-width 1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :background "#5b5b5b" :foreground "lightgreen" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     ;;(mode-line ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     ;;(mode-line-buffer-id ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     ;;(mode-line-emphasis ((t (:bold t :weight bold))))
     ;;(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     ;;(mode-line-inactive ((t (:background "gray20" :foreground "lemon chiffon" :box (:line-width 1 :style released-button)))))
     (modeline-mousable ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (modeline-mousable-minor-mode ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (mouse ((t (:background "white"))))
     (my-summary-highlight-face ((t (:background "PaleTurquoise4" :foreground "White"))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (my-url-face ((t (:foreground "LightBlue"))))
     (next-error ((t (:background "DarkCyan"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "SeaGreen2"))))
     (nxml-attribute-prefix ((t (:foreground "LightCoral"))))
     (nxml-attribute-value ((t (:foreground "burlywood"))))
     (nxml-attribute-value-delimiter ((t (:foreground "burlywood"))))
     (nxml-cdata-section-CDATA ((t (:foreground "LightCoral"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "gold"))))
     (nxml-char-ref-number ((t (:foreground "gold"))))
     (nxml-comment-content ((t (:italic t :slant italic :foreground "CadetBlue"))))
     (nxml-comment-delimiter ((t (:italic t :foreground "CadetBlue" :slant italic))))
     (nxml-delimited-data ((t (:bold t :weight bold :foreground "BlanchedAlmond"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:bold t :weight bold :foreground "goldenrod"))))
     (nxml-element-prefix ((t (:foreground "LightCoral"))))
     (nxml-entity-ref-delimiter ((t (:foreground "gold"))))
     (nxml-entity-ref-name ((t (:foreground "gold"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal :foundry "misc" :family "fixed"))))
     (nxml-hash ((t (:foreground "LightCoral"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "LightCoral"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "SeaGreen2"))))
     (nxml-namespace-attribute-value ((t (:foreground "burlywood"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "burlywood"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "LightCoral"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "#102e4e" :foreground "#eeeeee" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "Anonymous" :box 1 :height 105))))
     (nxml-outline-ellipsis ((t (:bold t :family "Anonymous" :foundry "unknown" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeee" :background "#102e4e" :stipple nil :weight bold :height 105))))
     (nxml-outline-indicator ((t (:family "Anonymous" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeee" :background "#102e4e" :stipple nil :height 105))))
     (nxml-processing-instruction-content ((t (:bold t :foreground "BlanchedAlmond" :weight bold))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (nxml-prolog-keyword ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (nxml-prolog-literal-content ((t (:bold t :foreground "BlanchedAlmond" :weight bold))))
     (nxml-prolog-literal-delimiter ((t (:bold t :foreground "BlanchedAlmond" :weight bold))))
     (nxml-ref ((t (:foreground "gold"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (paren-blink-off ((t (:foreground "gray80"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "gray30"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "RosyBrown" :foreground "gray30"))))
     (paren-mismatch-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (paren-no-match-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (pointer ((t (:background "#ffffff" :foreground "#000000"))))
     (primary-selection ((t (:background "blue"))))
     (py-XXX-tag-face ((t (:italic t :foreground "#3CB371" :slant italic))))
     (py-builtins-face ((t (:foreground "Cyan"))))
     (py-class-name-face ((t (:foreground "white"))))
     (py-decorators-face ((t (:foreground "Cyan"))))
     (py-exception-name-face ((t (:foreground "DeepSkyBlue1"))))
     (py-pseudo-keyword-face ((t (:foreground "Cyan"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "yellow"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "DarkCyan"))))
     (right-margin ((t (nil))))
     (rng-error ((t (:bold t :weight bold :foreground "yellow"))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (scroll-bar ((t (:background "gray" :foreground "#506070"))))
     (secondary-selection ((t (:background "yellow" :foreground "gray10"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "turquoise"))))
     (sgml-end-tag-face ((t (:foreground "aquamarine"))))
     (sgml-entity-face ((t (:foreground "gray85"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "brown"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-start-tag-face ((t (:foreground "aquamarine"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (shadow ((t (:foreground "grey70"))))
     (shell-option-face ((t (:foreground "gray85"))))
     (shell-output-2-face ((t (:foreground "gray85"))))
     (shell-output-3-face ((t (:foreground "gray85"))))
     (shell-output-face ((t (:bold t :weight bold))))
     (shell-prompt-face ((t (:foreground "yellow"))))
     (show-block-face1 ((t (:background "gray10"))))
     (show-block-face2 ((t (:background "gray15"))))
     (show-block-face3 ((t (:background "gray20"))))
     (show-block-face4 ((t (:background "gray25"))))
     (show-block-face5 ((t (:background "gray30"))))
     (show-block-face6 ((t (:background "gray35"))))
     (show-block-face7 ((t (:background "gray40"))))
     (show-block-face8 ((t (:background "gray45"))))
     (show-block-face9 ((t (:background "gray50"))))
     (show-paren-match ((t (:bold t :background "purple" :foreground "white" :weight bold))))
     (show-paren-mismatch ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (show-trailing-whitespace ((t (:background "red" :foreground "blue"))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "Gray85"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (speedbar-button-face ((t (:bold t :weight bold))))
     (speedbar-directory-face ((t (:bold t :weight bold))))
     (speedbar-file-face ((t (:bold t :weight bold))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "gray85" :weight bold))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default ((t (:background "gray80" :foreground "gray30" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "lucida console"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-green ((t (:foreground "green"))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellowbg ((t (:background "yellow"))))
     (tex-math-face ((t (:foreground "RosyBrown"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:background "Red3" :foreground "DarkSlateGray"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "#102e4e"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "#ffffff" :foreground "#000000"))))
     ;;(vhdl-font-lock-attribute-face ((t (:foreground "gray85"))))
     ;;(vhdl-font-lock-directive-face ((t (:foreground "gray85"))))
     ;;(vhdl-font-lock-enumvalue-face ((t (:foreground "gray85"))))
     ;;(vhdl-font-lock-function-face ((t (:foreground "gray85"))))
     ;;(vhdl-font-lock-prompt-face ((t (:bold t :foreground "gray85" :weight bold))))
     ;;(vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "gray85" :weight bold))))
     ;;(vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     ;;(vhdl-speedbar-architecture-face ((t (:foreground "gray85"))))
     ;;(vhdl-speedbar-architecture-selected-face ((t (:foreground "gray85" :underline t))))
     ;;(vhdl-speedbar-configuration-face ((t (:foreground "gray85"))))
     ;;(vhdl-speedbar-configuration-selected-face ((t (:foreground "gray85" :underline t))))
     ;;(vhdl-speedbar-entity-face ((t (:foreground "gray85"))))
     ;;(vhdl-speedbar-entity-selected-face ((t (:foreground "gray85" :underline t))))
     ;;(vhdl-speedbar-instantiation-face ((t (:foreground "gray85"))))
     ;;(vhdl-speedbar-instantiation-selected-face ((t (:foreground "gray85" :underline t))))
     ;;(vhdl-speedbar-package-face ((t (:foreground "gray85"))))
     ;;(vhdl-speedbar-package-selected-face ((t (:foreground "gray85" :underline t))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-from-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "gray30"))))
     (vmpc-pre-sig-face ((t (:foreground "gray85"))))
     (vmpc-sig-face ((t (:foreground "gray85"))))
     (vvb-face ((t (:background "pink" :foreground "gray30"))))
     (w3m-anchor-face ((t (:bold t :foreground "gray85" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "gray85" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     ;;(which-func ((t (:foreground "black"))))
     (which-func ((t (:foreground "#ADFF2F"))))
     ;;(white ((t (:foreground "white"))))
     (widget ((t (:background "gray75"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:background "white" :foreground "gray30"))))
     (xrdb-option-name-face ((t (:foreground "gray85"))))
     (xref-keyword-face ((t (:foreground "gray85"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "gray85"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "blue"))))
     (org-agenda-calendar-event ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeee" :background "#102e4e" :stipple nil :height 90))))
     (org-agenda-calendar-sexp ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeee" :background "#102e4e" :stipple nil :height 90))))
     (org-agenda-clocking ((t (:foreground "gray10" :background "yellow"))))
     (org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 90))))
     (org-agenda-current-time ((t (:foreground "LightGoldenrod"))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-diary ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeee" :background "#102e4e" :stipple nil :height 90))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-filter-category ((t (:box (:line-width 2 :style released-button) :foreground "black" :background "gray"))))
     (org-agenda-filter-tags ((t (:box (:line-width 2 :style released-button) :foreground "black" :background "gray"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:italic t :foreground "CadetBlue" :slant italic))))
     (org-block-end-line ((t (:italic t :foreground "CadetBlue" :slant italic))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "PaleGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Pink"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 90 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-date-selected ((t (:foreground "Pink" :weight normal))))
     (org-default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeee" :background "#102e4e" :stipple nil :height 90))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "grey70"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold :height 1.44))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "goldenrod" :weight bold))))
     (org-level-2 ((t (:foreground "SeaGreen2"))))
     (org-level-3 ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
     (org-level-4 ((t (:italic t :foreground "CadetBlue" :slant italic))))
     (org-level-5 ((t (:foreground "CadetBlue1"))))
     (org-level-6 ((t (:foreground "gold"))))
     (org-level-7 ((t (:foreground "LightCoral"))))
     (org-level-8 ((t (:foreground "burlywood"))))
     (org-link ((t (:underline t :foreground "cyan1"))))
     (org-meta-line ((t (:italic t :slant italic :foreground "CadetBlue"))))
     (org-mode-line-clock ((t (:box (:line-width 2 :style released-button) :foreground "black" :background "gray"))))
     (org-mode-line-clock-overrun ((t (:box (:line-width 2 :style released-button) :foreground "black" :background "red"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:foreground "yellow"))))
     )))
(add-to-list 'color-themes '(my-deep-blue  "THEME NAME" "YOUR NAME"))

(provide 'my-deep-blue)
