(eval-when-compile    (require 'color-theme))
(defun my-light-blue ()
  "Color theme by upi=PA0024320, created 2011-03-31."
  (interactive)
  (color-theme-install
   '(my-light-blue
     ((background-color . "#EDEDED")
      (background-mode . light)
      ;;(background-toolbar-color . "#e79ddf7ddf7d")
      ;;(border-color . "black")
      ;;(bottom-toolbar-shadow-color . "#8e3886178617")
      (cursor-color . "red3")
      (foreground-color . "black")
      (mouse-color . "white"))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Gray30"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Gray30"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Gray30"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Gray30"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eshell-ls-archive-face ((t (:bold t :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "gray85"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "gray85" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "Cyan" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "gray85"))))
     (eshell-ls-product-face ((t (:foreground "gray85"))))
     (eshell-ls-readonly-face ((t (:foreground "gray70"))))
     (eshell-ls-special-face ((t (:bold t :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :weight bold))))
     (eshell-ls-text-face ((t (:foreground "gray85"))))
     (eshell-ls-todo-face ((t (:bold t :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "gray85"))))
     (eshell-prompt-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :weight bold))))
     (eshell-test-ok-face ((t (:bold t :weight bold))))


     ;;(font-lock-builtin-face ((t (:foreground "LightCoral"))))
     (font-lock-builtin-face ((t (:foreground "#2F4F4F"))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "#800"))))
     (font-lock-comment-face ((t (:italic t :foreground "#800" :slant italic))))
     (font-lock-constant-face ((t (:foreground "black"))))
     (font-lock-doc-string-face ((t (:foreground "#080"))))
     ;;(font-lock-function-name-face ((t (:bold t :foreground "#040990"))))
     (font-lock-function-name-face
      ((t (:foreground "deep sky blue" :underline t :weight bold))))
     (font-lock-comment-face ((t (:foreground "lime green"))))
     (font-lock-comment-delimiter-face
      ((default (:inherit font-lock-comment-face :weight ultra-bold))
           (((class color) (min-colors 16)) nil)))
     ;;(font-lock-keyword-face ((t (:foreground "#2F4F4F" ))))
     (font-lock-keyword-face ((t (:foreground "gold" :weight bold))))
     (font-lock-other-emphasized-face ((t (:foreground "black" :weight bold))))
     (font-lock-other-type-face ((t (t :foreground "black" ))))
     (font-lock-preprocessor-face ((t (:foreground "#800"))))
     ;;(font-lock-string-face ((t (:foreground "#080"))))
     ;;(font-lock-string-face ((t (:foreground "#800"))))
     (font-lock-string-face ((t (:foreground "tomato" :slant italic))))
     ;;(font-lock-type-face ((t (:foreground "#617AFD"))))
     (font-lock-type-face ((t (:foreground "black"))))
     (font-lock-variable-name-face ((t (:foreground "black"))))
     ;;set the margin color
     ;;(fringe ((t (:background "#405060"))))
     

     (highlight ((t (:background "darkgreen"))))
     (highlight-changes-delete-face ((t (:foreground "gray85" :underline t))))
     (highlight-changes-face ((t (:foreground "gray85"))))
     (highlight-symbol-face ((t (:background "gray30"))))
     (highline-face ((t (:background "#3c5473"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (holiday-face ((t (:background "pink" :foreground "green"))))

     (ido-first-match ((t (:foreground "black" :bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "yellow"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-subdir-face ((t (:foreground "red"))))

     (mode-line ((t (:background "RoyalBlue4" :foreground "mistyRose" :box (:line-width 1 :style released-button)))))
     (mode-line ((t (:background "RoyalBlue4" :foreground "Gold" :box (:line-width 1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :background "#5b5b5b" :foreground "lightgreen" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline-mousable ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (modeline-mousable-minor-mode ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (mouse ((t (:background "white"))))
     (my-summary-highlight-face ((t (:background "PaleTurquoise4" :foreground "White"))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (my-url-face ((t (:foreground "LightBlue"))))
     (next-error ((t (:background "DarkCyan"))))
     (nil ((t (nil))))
     (py-XXX-tag-face ((t (:italic t :foreground "#3CB371" :slant italic))))
     (py-builtins-face ((t (:foreground "#5F67D4"))))
     (py-class-name-face ((t (:foreground "black"))))
     (py-decorators-face ((t (:foreground "Cyan"))))
     (py-exception-name-face ((t (:italic t :foreground "white" :slant italic))))
     (py-pseudo-keyword-face ((t (:foreground "Cyan"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "blue"))))
     )))
(add-to-list 'color-themes '(my-light-blue  "THEME NAME" "YOUR NAME"))

(provide 'my-light-blue)
